### ISSUE TITLE
hello for sms 

### ISSUE THREAD

**Issue by KielVoid** [entynetproject/quack#10]
Traceback (most recent call last):
  File "./quack", line 127, in <module>
    main()
  File "./quack", line 118, in main
    import tools.addons.clean
ModuleNotFoundError: No module named 'tools.addons'

**Comment by enty8080** [comment]
What OS?

**Comment by KielVoid** [comment]
Kali Linux .

**Comment by enty8080** [comment]
Very strange because it works well on Kali Linux for me with Python3.

**Comment by KielVoid** [comment]
it is strange. i tried re cloning it. and stil got the same error. 
how do i install the tools.addons module ?

**Comment by LimerBoy** [comment]
> Very strange because it works well on Kali Linux for me with Python3.

Удачного исправления моих багов :)

**Comment by enty8080** [comment]
Please send me full command that returns this error.

**Comment by enty8080** [comment]
Try:
```
chmod +x install.sh
./install.sh
/bin/quack
```

**Comment by KielVoid** [comment]
root@localhost:~/quack# quack --tool SMS --target 639516042271 --time 10 --threads 10
Traceback (most recent call last):
  File "./quack", line 127, in <module>
    main()
  File "./quack", line 118, in main
    import tools.addons.clean
ModuleNotFoundError: No module named 'tools.addons'

Other tools inside Quack works. The sms tool gives me errors

**Comment by enty8080** [comment]
In this video, one guy uses latest kali + payhon3, and all looks well, I think that the problem is not in the Quack Toolkit, problem in your system or you have broken dependencies installed.
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dg57tUSSWmqc&psig=AOvVaw3_r2R0QZ1l7VJtOEwXsRXL&ust=1587797655105000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCKCIrKy9gOkCFQAAAAAdAAAAABAD

**Comment by enty8080** [comment]
This is a video tutorial, watch this video, it can solve your problem.

**Comment by Nasratullah-salehi** [comment]
i also have error


Traceback (most recent call last):
  File "./quack", line 124, in <module>
    main()
  File "./quack", line 117, in main
    from tools.SMS.main import SMS_ATTACK
  File "/root/quack/tools/SMS/main.py", line 6, in <module>
    import tools.SMS.sendRequest as request
  File "/root/quack/tools/SMS/sendRequest.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
