### ISSUE TITLE
Application continue sending sms even after timeout.

### ISSUE THREAD

**Issue by FabxBs** [entynetproject/quack#11]
I did a test on my phone, was working fine with the spam, but for some reason even after the timeout, sometimes after like 10 min or more, i get only one message from one of those numbers. Of couse i can block the numbers, just want to know if it's a bug or something related to internet connection, dunno if it's just a temporary thing. I tried to redirect the spam to an unexistent number, it seems that it has stopped. Also i was on a virtual machine.

**Comment by enty8080** [comment]
Sorry, but this is not a problem.
