### ISSUE TITLE
No Internet connection! Error 

### ISSUE THREAD

**Issue by smsheesali** [entynetproject/quack#20]
I  am using latest kali linux version when I am installing by using following command 
sudo ./install.sh 
It shows following error although my internet is working properly.
No Internet connection!

**Comment by neiry** [comment]
> I am using latest kali linux version when I am installing by using following command
> sudo ./install.sh
> It shows following error although my internet is working properly.
> No Internet connection!

sudo ./install.sh

**Comment by neiry** [comment]
> I am using latest kali linux version when I am installing by using following command
> sudo ./install.sh
> It shows following error although my internet is working properly.
> No Internet connection!

use brain man ))

**Comment by smsheesali** [comment]
> > I am using latest kali linux version when I am installing by using following command
> > sudo ./install.sh
> > It shows following error although my internet is working properly.
> > No Internet connection!
> 
> use brain man ))

WHAT ???

**Comment by game-lover** [comment]
Do you use virtual machine?

**Comment by smsheesali** [comment]
Yeah I using it on Virtual BOX

**Comment by game-lover** [comment]
This is problem of virtual machines, you can try to delete

```bash
{
ASESR="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
} &> /dev/null
if [[ "$ASESR" != 0 ]]
then 
   echo -e ""$E"No Internet connection!"
   exit
fi
```
 from install.sh

**Comment by game-lover** [comment]
@enty8080 report neiry

**Comment by neiry** [comment]
> @enty8080 report neiry

да мне пофигу в принципе, краснодар маленький )))  а репорт за то что я чуваку сказал с рута запустить??? ты гений просто

**Comment by smsheesali** [comment]
Thanks man it worked.

**Comment by game-lover** [comment]
@niery
он и так запускал от рута, если ты не видел
