### ISSUE TITLE
HTTPConnection  Failed to establish a new connection

### ISSUE THREAD

**Issue by KeinWeb** [entynetproject/quack#23]
A few packets are going to send, but then it gives me thousends of errors like shown on this picture.
Pls help whats the problem
![Screenshot_1](https://user-images.githubusercontent.com/39127504/85798948-b1f99280-b73e-11ea-8832-4a071dfd9044.png)

**Comment by KeinWeb** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/39127504/85799477-8b882700-b73f-11ea-9e22-cf4c582129a1.png)

**Comment by KeinWeb** [comment]
?

**Comment by enty8080** [comment]
This is not a Quack issue. Quack works perfectly, maybe problem in site or urllib3, try reinstall it.
