### ISSUE TITLE
Error while using SLOWLORIS

### ISSUE THREAD

**Issue by PhillTV** [entynetproject/quack#24]
So when i want to use slowloris it shows me this Error:
`[*] Starting thread 1158...
Exception in thread Thread-1084:
Traceback (most recent call last):
[*] Starting thread 1159...
libgcc_s.so.1 must be installed for pthread_cancel to work
Exception in thread Thread-1128:
/usr/local/bin/quack: line 118:  6700 Aborted                 (core dumped) ./quack $1 $2 $3 $4 $5 $6 $7 $8 $9`
i tried to install libgcc_s,libgcc but it didnt worked for me

**Comment by Hcksfof** [comment]
Try removing the tool with **sudo rm -r quack/** and cloning it again with git. Then install the needed dependencies from **requirements.txt**

**Comment by enty8080** [comment]
gcc issue
