### ISSUE TITLE
No module named 'phonenumbers'

### ISSUE THREAD

**Issue by 10ke5h** [entynetproject/quack#25]
Please help me with this...

Traceback (most recent call last):
  File "./quack", line 146, in <module>
    main()
  File "./quack", line 139, in main
    from tools.SMS.main import SMS_ATTACK
  File "/root/quack/tools/SMS/main.py", line 28, in <module>
    import tools.SMS.sendRequest as request
  File "/root/quack/tools/SMS/sendRequest.py", line 27, in <module>
    import tools.SMS.numberTools as numberTools
  File "/root/quack/tools/SMS/numberTools.py", line 25, in <module>
    from phonenumbers import geocoder, parse
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by Hcksfof** [comment]
Try installing the needed dependencies from **requirements.txt**

**Comment by 10ke5h** [comment]
Command not found after running...
pip install -r requirements.txt (Python 2), or pip3 install -r requirements.txt (Python 3)

**Comment by Hcksfof** [comment]
Try **sudo pip install phonenumbers**

**Comment by Hcksfof** [comment]
@10ke5h Did it work?

**Comment by 10ke5h** [comment]
> @10ke5h Did it work?

Nope it didn't

**Comment by enty8080** [comment]
@10ke5h try execute `./install.sh` it should install all dependencies, or install it manually:
```
pip3 install -r requirements.txt
```

or

```
pip3 install phonenumbers
```

**Comment by 10ke5h** [comment]
worked on termux but not on kali...
