### ISSUE TITLE
Quack error permisión denied.

### ISSUE THREAD

**Issue by elputoivan** [entynetproject/quack#27]
![Screenshot_20200723-213645](https://user-images.githubusercontent.com/67056973/88331083-b3fa4580-cd2c-11ea-8ddc-f9cc7d258073.png)
![Screenshot_20200723-213427](https://user-images.githubusercontent.com/67056973/88331101-bb215380-cd2c-11ea-98be-c3ec3c24d72a.png)
![Screenshot_20200723-213856](https://user-images.githubusercontent.com/67056973/88331274-fde32b80-cd2c-11ea-8699-629c14ab8c57.png)

**Comment by enty8080** [comment]
run it as root and use bash for default shell.
