### ISSUE TITLE
Invalid syntax in print()

### ISSUE THREAD

**Issue by matrn** [entynetproject/quack#3]
Hello,
on this line: https://github.com/entynetproject/quack/blob/5161b2d773dfecafeb2c4eb3ca83a165a14c7f2e/tools/ipTools.py#L42 you have `;31m"+[-]+"\033[` which causes syntax error in print. I am not sure what `[-]` should do so I cannot fix it and pull request it.

**Comment by yhl5555** [comment]
[root@instance-1 quack]# ./quack --method HTTP --target https://www.****.com/ --time 10 --threads 10000


  █████   █    ██  ▄▄▄       ▄████▄   ██ ▄█▀
▒██▓  ██▒ ██  ▓██▒▒████▄    ▒██▀ ▀█   ██▄█▒ 
▒██▒  ██░▓██  ▒██░▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ 
░██  █▀ ░▓▓█  ░██░░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ 
░▒███▒█▄ ▒▒█████▓  ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄
░░ ▒▒░ ▒ ░▒▓▒ ▒ ▒  ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒
 ░ ▒░  ░ ░░▒░ ░ ░   ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░
   ░   ░  ░░░ ░ ░   ░   ▒   ░        ░ ░░ ░ 

Traceback (most recent call last):
  File "./quack", line 118, in <module>
    main()
  File "./quack", line 93, in main
    from tools.L7.http import HTTP_ATTACK
  File "/root/quack/tools/L7/http.py", line 31, in <module>
    import tools.ipTools as ipTools
  File "/root/quack/tools/ipTools.py", line 42
    print("\033[1;31m"+[-]+"\033[0m"+"Unable to verify if victim's IP address belong to a CloudFlare\'s subnet!")
                         ^
SyntaxError: invalid syntax
[root@instance-1 quack]#

**Comment by enty8080** [comment]
Ok, I’ll fix this

**Comment by enty8080** [comment]
Error fixed, enjoy tool!
