### ISSUE TITLE
the tool works good in sms sending but http it says couldorsomething or veryfication thanks to the developper

### ISSUE THREAD

**Issue by wolfyy59** [entynetproject/quack#4]

**Comment by enty8080** [comment]
?

**Comment by dydfrancis** [comment]
i keep getting error in sms sending please i need a good format on how to send sms thanks

**Comment by dydfrancis** [comment]
i keep getting error in sms sending please i need a good format on how to send sms thanks dydfrancis10@gmail.com

**Comment by enty8080** [comment]
`quack --tool SMS --target <phone> --time <time> --threads <threads>`
