### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by pestxxo** [entynetproject/quack#5]
http error, what should I do? Thanks

TabError: inconsistent use of tabs and spaces in indentation
root@server1:~/quack# quack --tool HTTP --target cyberwarblog.xyz --time 20 --threads 10

   █████   █    ██  ▄▄▄       ▄████▄   ██ ▄█▀
 ▒██▓  ██▒ ██  ▓██▒▒████▄    ▒██▀ ▀█   ██▄█▒ 
 ▒██▒  ██░▓██  ▒██░▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ 
 ░██  █▀ ░▓▓█  ░██░░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ 
 ░▒███▒█▄ ▒▒█████▓  ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄
 ░░ ▒▒░ ▒ ░▒▓▒ ▒ ▒  ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒
  ░ ▒░  ░ ░░▒░ ░ ░   ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░
    ░   ░  ░░░ ░ ░   ░   ▒

Traceback (most recent call last):
  File "./quack", line 127, in <module>
    main()
  File "./quack", line 102, in main
    from tools.L7.http import HTTP_ATTACK
  File "/root/quack/tools/L7/http.py", line 40
    if not input("\033[1;77m"+"[?]"+"\033[0m"+"Continue HTTP attack? (y/N): ") in ("y", "Y", "1"):
                                                                                                 ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by enty8080** [comment]
You want to DDoS the cyberwarblog?
Ok, I'll fix this.

**Comment by enty8080** [comment]
This error was fixed in 10secs
