### ISSUE TITLE
...

### ISSUE THREAD

**Issue by LimerBoy** [entynetproject/quack#6]
0

**Comment by enty8080** [comment]
Добрый день, я допустил ошибку что не сделал форк и не указал вас, но мне очень понравился ваш код и мне захотелось немного его разнообразить, поменять дизайн, исправить проблемы и грамматические ошибки.

**Comment by enty8080** [comment]
Я вас укажу как разработчика, а себя как дизайнера.

**Comment by enty8080** [comment]
Если вы не против?

**Comment by LimerBoy** [comment]
Окэй

**Comment by LimerBoy** [comment]
Ожидаю ссылку на свой гитхаб : /

**Comment by LimerBoy** [comment]
...

**Comment by enty8080** [comment]
I defined you on Entynetproject's site as a Quack Toolkit main developer, `https://entynetproject.org/quack/`
